# Generated by Django 4.2.7 on 2023-12-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
