# Generated by Django 4.2.7 on 2023-12-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_remove_order_product_remove_order_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
